# Generated by Django 4.1.13 on 2024-04-28 17:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("post_id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="images/")),
                ("create_time", models.DateField(auto_now_add=True, null=True)),
                ("caption", models.TextField(max_length=400)),
                ("tags", models.TextField(blank=True, max_length=200, null=True)),
                ("no_of_likes", models.IntegerField(default=0, null=True)),
                ("no_of_comments", models.IntegerField(default=0, null=True)),
            ],
            options={
                "db_table": "post",
            },
        ),
        migrations.CreateModel(
            name="SavedCollection",
            fields=[
                (
                    "saved_collection_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("no_of_posts", models.IntegerField(default=0, null=True)),
            ],
            options={
                "db_table": "saved_collection",
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.TextField(max_length=50)),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address."
                            )
                        ],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=4096,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_password_format",
                                message="Password must contain atleast 1 uppercase letter, 1 special character, and 1 number and be atleast 5 characters long.",
                                regex="^(?=.*[A-Z])(?=.*[!@#$%^&*])(?=.*[0-9]).{5,}$",
                            )
                        ],
                    ),
                ),
                ("no_of_posts", models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="SavedItem",
            fields=[
                ("saved_item_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.post"
                    ),
                ),
                (
                    "saved_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.savedcollection",
                    ),
                ),
            ],
            options={
                "db_table": "saved_item",
            },
        ),
        migrations.AddField(
            model_name="savedcollection",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="home.users"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="home.users"
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("commented_text", models.TextField(max_length=250)),
                (
                    "commented_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="home.users"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="home.post"
                    ),
                ),
            ],
            options={
                "db_table": "comment",
            },
        ),
    ]
