# Generated by Django 4.1.13 on 2024-04-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="bio",
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="name",
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
