# Generated by Django 4.1.13 on 2024-05-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_likedpost"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="saveditem",
            unique_together={("saved_collection", "post")},
        ),
    ]
